;
; This code is automatically generated by the FormDesigner.
; Manual modification is possible to adjust existing commands, but anything else will be dropped when the code is compiled.
; Event procedures needs to be put in another source file.
;

Enumeration FormWindow
  #Main
EndEnumeration

Enumeration FormGadget
  #WebView_0
  #Input
  #btnSend
  #UserList
  #ButtonImage_0
EndEnumeration

#HTMLPrefix$ = ~"\t\t\t<li class=\"msg-user\"><div class=\"msg-user\">"
#HTMLSuffix$ = ~"</div></li>\r\n\t\t</ul>"

Declare SetBrowserEmulation()
Declare UISendMessage()

;SetBrowserEmulation()

Procedure OpenMain(x = 0, y = 0, width = 640, height = 480)
  OpenWindow(#Main, x, y, width, height, "R2C2", #PB_Window_SystemMenu | #PB_Window_MinimizeGadget)
  WebGadget(#WebView_0, 10, 10, 440, 420,GetCurrentDirectory()+ "mainview.html#bottom")
  WebgadgetDisableScriptError(#WebView_0)
  
  StringGadget(#Input, 10, 440, 510, 25, "")
  GadgetToolTip(#Input, "Ecrivez votre message ou votre commande ici")
  
  ButtonGadget(#btnSend, 530, 440, 100, 25, "Envoyer")
  ListIconGadget(#UserList, 460, 10, 170, 420, "Utilisateurs", 165, #PB_ListIcon_MultiSelect | #PB_ListIcon_FullRowSelect)
  ButtonImageGadget(#ButtonImage_0, 610, 480, 100, 25, 0)
  
  AddKeyboardShortcut(#Main,#PB_Shortcut_Return,#btnSend)
  
  BindGadgetEvent(#btnSend,@UISendMessage())
  BindEvent(#btnSend,@UISendMessage(),#Main)
EndProcedure

OpenMain()

Repeat
  event = WaitWindowEvent()
  
  If event = #PB_Event_Menu And EventMenu() = #btnSend
    UISendMessage()
  EndIf
  
Until event = #PB_Event_CloseWindow



Procedure UISendMessage()
  Protected Message$ = GetGadgetText(#Input)
  
  Debug GetGadgetAttribute(#WebView_0,#PB_Web_ScrollY)
  
  If 1
    OpenFile(1,"mainview.html",#PB_File_SharedWrite)
    HTML$ = ReadString(1,#PB_File_IgnoreEOL)
    
    FileSeek(1,0)
    
    WriteStringN(1, StringField(HTML$,1,"</ul>") +#HTMLPrefix$+ Message$ +#HTMLSuffix$+ StringField(HTML$,2,"</ul>"), #PB_UTF8)
    
    CloseFile(1)
    
    SetGadgetState(#WebView_0,#PB_Web_Refresh)
    SetGadgetText(#WebView_0,GetCurrentDirectory()+ "mainview.html#bottom")
    SetGadgetAttribute(#WebView_0,#PB_Web_ScrollY,10)
    
    SetGadgetText(#Input,"")
  Else
    SetGadgetText(#Input,"Une erreur s'est produite lors de l'envoi du message")
  EndIf
  
EndProcedure


Procedure SetBrowserEmulation() ; permet de choisir le type de navigateur qu'on veux
                                ; https://msdn.microsoft.com/en-us/library/ee330730(v=vs.85).aspx
  Protected IEVersion.s = "2AF9"; setting the desired IE-Version (see below)
  Protected RegistryString.s
  Protected TempRegFile.s
  Protected FF
  RegistryString = "Windows Registry Editor Version 5.00" + #CRLF$ +
                   "" + #CRLF$ +
                   "[HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION]" + #CRLF$ +
                   Chr(34) + GetFilePart(ProgramFilename()) + Chr(34) + "=dword:" + IEVersion + #CRLF$
  
  TempRegFile = GetTemporaryDirectory() + "SetBrowserEmulation.reg"  
  FF = CreateFile(#PB_Any, TempRegFile)
  If FF
    WriteString(FF, RegistryString)
    CloseFile(FF)
    RunProgram("regedit", "/s " + Chr(34) + TempRegFile + Chr(34), "",  #PB_Program_Wait)
    DeleteFile(TempRegFile)
    ProcedureReturn #True
  EndIf
EndProcedure


; IDE Options = PureBasic 5.60 (Windows - x64)
; CursorPosition = 78
; FirstLine = 71
; Folding = -
; EnableXP